import { CHANNEL_LABEL } from '../data/network';
import { languageInfo } from '../data/languages';
import type { DeliveryRecord, EmergencyAlert, LanguageCode } from '../types';
import { visualRows } from './content';

export const DEMO_DISCLAIMER = 'SYNTHETIC DEMO DATA — NOT A REAL EMERGENCY ALERT';

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    ta.remove();
    return ok;
  }
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const csvCell = (v: string | number) => `"${String(v).replace(/"/g, '""')}"`;

export function downloadDeliveryCsv(alert: EmergencyAlert, records: DeliveryRecord[]) {
  const header = ['Recipient', 'Group', 'Language', 'Format', 'Communication Mode', 'Channel History', 'Status', 'Last Update', 'Acknowledgement', 'Retries', 'Hops', 'Sim Delivery Time (s)'];
  const rows = records.map((r) => [
    r.recipient.name,
    r.recipient.persona,
    languageInfo(r.language).name,
    r.format,
    CHANNEL_LABEL[r.channel],
    r.channelHistory.map((c) => CHANNEL_LABEL[c]).join(' > '),
    r.status,
    new Date(r.timestamp).toISOString(),
    r.acknowledged ?? '',
    r.retryCount,
    r.hops,
    r.simSeconds.toFixed(1),
  ]);
  const lines = [
    [csvCell(DEMO_DISCLAIMER)],
    [csvCell(`Alert ${alert.id} — SIMULATED DELIVERY REPORT — no real messages were sent`)],
    header.map(csvCell),
    ...rows.map((r) => r.map(csvCell)),
  ];
  download(new Blob([lines.map((l) => l.join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }), `${alert.id}-delivery-report.csv`);
}

const SEVERITY_FILL: Record<string, string> = { INFO: '#0e7490', WARNING: '#c2410c', HIGH: '#b91c1c', CRITICAL: '#7f1d1d' };

/** Draws the visual alert on a canvas (no external libraries) and downloads a PNG. */
export function downloadVisualPng(alert: EmergencyAlert, lang: LanguageCode) {
  const v = visualRows(alert, lang);
  const W = 1080;
  const H = 1350;
  const canvas = document.createElement('canvas');
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const font = (size: number, weight = 700) => `${weight} ${size}px system-ui, "Noto Sans", "Noto Sans Devanagari", "Noto Sans Oriya", "Noto Sans Bengali", sans-serif`;

  ctx.fillStyle = '#0a0f1c';
  ctx.fillRect(0, 0, W, H);
  ctx.fillStyle = SEVERITY_FILL[alert.severity] ?? '#b91c1c';
  ctx.fillRect(0, 0, W, 260);
  ctx.fillStyle = '#ffffff';
  ctx.strokeStyle = '#ffffff';
  ctx.lineWidth = 8;
  ctx.beginPath();
  ctx.moveTo(115, 60);
  ctx.lineTo(180, 190);
  ctx.lineTo(50, 190);
  ctx.closePath();
  ctx.stroke();
  ctx.fillRect(111, 100, 8, 50);
  ctx.fillRect(111, 163, 8, 8);
  ctx.font = font(64);
  wrap(ctx, v.headline, 220, 120, W - 280, 70);
  ctx.font = font(40, 600);
  ctx.fillText(`● ${v.severity}`, 220, 220);

  let y = 340;
  for (const row of v.rows) {
    ctx.fillStyle = '#111a2e';
    roundRect(ctx, 40, y, W - 80, 200, 28);
    ctx.fill();
    ctx.fillStyle = { location: '#38bdf8', time: '#fbbf24', action: '#34d399', donot: '#f87171' }[row.icon];
    ctx.beginPath();
    ctx.arc(125, y + 100, 38, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#94a3b8';
    ctx.font = font(34, 700);
    ctx.fillText(row.label, 200, y + 65);
    ctx.fillStyle = row.tone === 'donot' ? '#fca5a5' : '#f8fafc';
    ctx.font = font(46, 800);
    wrap(ctx, row.value, 200, y + 125, W - 280, 54);
    y += 225;
  }
  ctx.fillStyle = '#facc15';
  ctx.fillRect(0, H - 140, W, 140);
  ctx.fillStyle = '#111827';
  ctx.font = font(34, 800);
  ctx.fillText(DEMO_DISCLAIMER, 50, H - 82);
  ctx.font = font(26, 600);
  ctx.fillText(`VISUAL VERSION · ${alert.id} · ${languageInfo(lang).name} · generated by LASTMILE demo templates`, 50, H - 38);

  canvas.toBlob((blob) => blob && download(blob, `${alert.id}-${lang}-visual.png`), 'image/png');
}

function wrap(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxWidth: number, lineHeight: number) {
  const words = text.split(' ');
  let line = '';
  let yy = y;
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line, x, yy);
      line = word;
      yy += lineHeight;
    } else line = test;
  }
  ctx.fillText(line, x, yy);
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

const escapeHtml = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] ?? c);

/** Opens a print-friendly window for the alert; the official text is always included. */
export function printAlert(alert: EmergencyAlert, lang: LanguageCode, plain: string) {
  const v = visualRows(alert, lang);
  const w = window.open('', '_blank', 'width=800,height=900');
  if (!w) return false;
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${alert.id} — Demo print</title>
<style>body{font-family:system-ui,sans-serif;margin:32px;color:#111}h1{margin:0 0 4px}.banner{background:#facc15;padding:10px 14px;font-weight:800;border:2px solid #111;margin-bottom:18px}
.box{border:2px solid #111;padding:14px 16px;margin:14px 0;border-radius:8px}.tag{font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}
.row{font-size:22px;margin:8px 0}pre{white-space:pre-wrap;font:inherit;font-size:18px}</style></head><body>
<div class="banner">${DEMO_DISCLAIMER}</div>
<h1>${escapeHtml(v.headline)} — ${escapeHtml(v.severity)}</h1>
<div class="box"><div class="tag">Visual version · ${languageInfo(lang).name} · generated demo content</div>
${v.rows.map((r) => `<div class="row"><b>${escapeHtml(r.label)}:</b> ${escapeHtml(r.value)}</div>`).join('')}</div>
<div class="box"><div class="tag">Plain language · simplified demo content</div><pre>${escapeHtml(plain)}</pre></div>
<div class="box"><div class="tag">Official source content (unaltered) · ${alert.id}</div><pre>${escapeHtml(alert.originalMessage)}</pre></div>
<script>window.onload=()=>{window.print()}</script></body></html>`);
  w.document.close();
  return true;
}
